/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type PayeeStruct = {
  account: string;
  shares: BigNumberish;
  transfersAllowedWhileLocked: boolean;
};

export type PayeeStructOutput = [string, number, boolean] & {
  account: string;
  shares: number;
  transfersAllowedWhileLocked: boolean;
};

export type SliceParamsStruct = {
  payees: PayeeStruct[];
  minimumShares: BigNumberish;
  currencies: string[];
  releaseTimelock: BigNumberish;
  transferTimelock: BigNumberish;
  controller: string;
  slicerFlags: BigNumberish;
  sliceCoreFlags: BigNumberish;
};

export type SliceParamsStructOutput = [
  PayeeStructOutput[],
  BigNumber,
  string[],
  BigNumber,
  number,
  string,
  number,
  number
] & {
  payees: PayeeStructOutput[];
  minimumShares: BigNumber;
  currencies: string[];
  releaseTimelock: BigNumber;
  transferTimelock: number;
  controller: string;
  slicerFlags: number;
  sliceCoreFlags: number;
};

export interface ISlicerManagerInterface extends utils.Interface {
  contractName: "ISlicerManager";
  functions: {
    "_createSlicer(address,uint256,((address,uint32,bool)[],uint256,address[],uint256,uint40,address,uint8,uint8))": FunctionFragment;
    "_upgradeSlicers(address)": FunctionFragment;
    "implementation()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_createSlicer",
    values: [string, BigNumberish, SliceParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "_upgradeSlicers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_createSlicer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_upgradeSlicers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISlicerManager extends BaseContract {
  contractName: "ISlicerManager";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISlicerManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _createSlicer(
      creator: string,
      id: BigNumberish,
      params: SliceParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    implementation(overrides?: CallOverrides): Promise<[string]>;
  };

  _createSlicer(
    creator: string,
    id: BigNumberish,
    params: SliceParamsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _upgradeSlicers(
    newLogicImpl: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  implementation(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _createSlicer(
      creator: string,
      id: BigNumberish,
      params: SliceParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    implementation(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _createSlicer(
      creator: string,
      id: BigNumberish,
      params: SliceParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _createSlicer(
      creator: string,
      id: BigNumberish,
      params: SliceParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
