/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ISliceProductPriceInterface extends utils.Interface {
  contractName: "ISliceProductPrice";
  functions: {
    "productPrice(uint256,uint256,address,uint256,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "productPrice",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "productPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISliceProductPrice extends BaseContract {
  contractName: "ISliceProductPrice";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISliceProductPriceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    productPrice(
      slicerId: BigNumberish,
      productId: BigNumberish,
      currency: string,
      quantity: BigNumberish,
      buyer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { ethPrice: BigNumber; currencyPrice: BigNumber }
    >;
  };

  productPrice(
    slicerId: BigNumberish,
    productId: BigNumberish,
    currency: string,
    quantity: BigNumberish,
    buyer: string,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { ethPrice: BigNumber; currencyPrice: BigNumber }
  >;

  callStatic: {
    productPrice(
      slicerId: BigNumberish,
      productId: BigNumberish,
      currency: string,
      quantity: BigNumberish,
      buyer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { ethPrice: BigNumber; currencyPrice: BigNumber }
    >;
  };

  filters: {};

  estimateGas: {
    productPrice(
      slicerId: BigNumberish,
      productId: BigNumberish,
      currency: string,
      quantity: BigNumberish,
      buyer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    productPrice(
      slicerId: BigNumberish,
      productId: BigNumberish,
      currency: string,
      quantity: BigNumberish,
      buyer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
